// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import express, {Request, Response} from 'express';

const router = express.Router();

/**
 * @description Gets a cloud run service from gcp platform.
 * @param {Request}     req Incoming request
 * @param {Response}    res Outgoing response
 * @returns {Response}      A 200 status indicates the API is healthy and running
 */


router.get('/', async (req: Request, res: Response) => {
  const { serviceName } = req.query
  
    const name = 'projects/bkzge7-dev/locations/us-central1/services/' + serviceName
  
    // Imports the Run library
    const {ServicesClient} = require('@google-cloud/run').v2;
  
    // Instantiates a client
    const runClient = new ServicesClient();
  
    //async function callGetService() {
    try{
      // Construct request
        const request = {
        name,
        };
        // Run request
        const response = await runClient.getService(request);
        return res.json({status: 200, response: response[0]})
     }catch(err){
        console.log(err)
            return res.json({status: 400, response: "no service"});
      }

})

module.exports = router;
